### ISSUE TITLE
Sequential prints shown as parrallel

### ISSUE THREAD

**Issue by k2OS** [hudbrog/gCodeViewer#15]
I'm not sure if I am missing an option somewhere, but I seriously thought slic3r didn't want to make sequential prints as gcode.ws shows all my parts in the same height and being printed in parrallel.. I didn't even test printing anything, as I thought gcode was right and slic3r was wrong. 

Is there a setting I am issing? I tried disabling a few things here and there, but couldn't make the site show me the prints as I thought it would happen.

Otherwise _great_ job. It really has saved precious time by analyzing my code before printing it :)

**Comment by dartrax** [comment]
Just wanted to say hello and that I started to use sequentially pinting because it has some advantages... If I print 20 objects at once and in the middle of the print one layer has a fault, I lose all 20 half-way-printed parts. With sequential printing, I have 9 objects perfectly finished, 1 object is lost and 10 objects are not yet started to print, so no waste.
It should be noted somewhere that gCodeViewer does not display sequentially printing correct, because currently everybody assumes that the slicer made an error, not gCodeViewer, when the preview shows all objects started at once even with "sort by Z order" option disabled.
